.TH tcpsvd 8
.SH NAME
tcpsvd \- TCP/IP service daemon
.SH SYNOPSIS
.B tcpsvd
[\-dEHv] [\-c
.I num\fR] [\-u
.I user\fR] [\-r
.I dir
| \-x
.I cdb\fR]
.I host
.I port
.I prog
.SH DESCRIPTION
.SH OPTIONS
.TP
.I host
.I host
either is a hostname, or a dotted-decimal IP address, or 0.
If
.I host
is 0,
.B tcpsvd
accepts connections to any local IP address.
.TP
.I port
.B tcpsvd
accepts connections to
.IR host :\fIport\fR.
.TP
.I prog
.I prog
consists of one or more arguments.
For each connection,
.B tcpsvd
runs
.IR prog ,
with descriptor 0 reading from the network and descriptor 1 writing to the
network.
By default it also sets up TCP-related environment variables, see
.BR tcp-environ (5)
.TP
.B \-c \fInum
concurrency.
Handle up to
.I num
concurrent connections.
Default is 30.
.TP
.B \-u \fIuser
drop permissions.
Switch user ID to
.IR user 's
UID, and group ID to
.IR user 's
primary GID, before starting
.I prog
to handle the connection.
.TP
.B \-r \fIdir
rules directory.
.TP
.B \-x \fIcdb
rules cdb.
.TP
.B \-d
deny.
.TP
.B \-E
no ucspi environment.
Do not set up TCP-related environment variables.
.TP
.B \-H
no remote hostname lookup.
.TP
.B \-v
verbose.
Print verbose messsages to standard out.
.SH SEE ALSO
ipsvd-cdb(8),
udpsvd8)
.P
http://smarden.org/ipsvd/
.SH AUTHOR
Gerrit Pape <pape@smarden.org>
