.TH tcpsvd 8
.SH NAME
tcpsvd \- TCP/IP service daemon
.SH SYNOPSIS
.B tcpsvd
[\-nEHv] [\-c
.I n\fR] [\-b
.I n\fR] [\-u
.I user\fR] [\-i
.IR dir |\-x
.I cdb\fR]
.I host
.I port
.I prog
.SH DESCRIPTION
.B tcpsvd
creates a TCP/IP socket, binds it to the address
.IR host :\fIprog\fR,
and listens on the socket for incoming connections.
.P
On each incoming connection,
.B tcpsvd
conditionally runs a program, with standard input reading from the socket,
and standard output writing to the socket, to handle this connection.
.B tcpsvd
keeps listening on the socket for new connections, and can handle multiple
connections simultaneously.
.P
.B tcpsvd
optionally checks for special intructions depending on the IP address of the
client that initiated the connection, see
.BR ipsvd-instruct (5).
.SH OPTIONS
.TP
.I host
.I host
either is a hostname, or a dotted-decimal IP address, or 0.
If
.I host
is 0,
.B tcpsvd
accepts connections to any local IP address.
.TP
.I port
.B tcpsvd
accepts connections to
.IR host :\fIport\fR.
.TP
.I prog
.I prog
consists of one or more arguments.
For each connection,
.B tcpsvd
normally runs
.IR prog ,
with file descriptor 0 reading from the network, and file descriptor 1
writing to the network.
By default it also sets up TCP-related environment variables, see
.BR tcp-environ (5)
.TP
.B \-c \fIn
concurrency.
Handle up to
.I n
connections simultaneously.
Default is 30.
If there are
.I n
connections active,
.B tcpsvd
defers acceptance of a new connection until an active connection is closed.
.TP
.B \-u \fIuser
drop permissions.
Switch user ID to
.IR user 's
UID, and group ID to
.IR user 's
primary GID after creating and binding to the socket.
.TP
.B \-i \fIdir
read instructions for handling new connections from the instructions
directory
.IR dir .
See
.BR ipsvd-instruct (5)
for details.
.TP
.B \-x \fIcdb
read instructions for handling new connections from the constant database
.IR cdb .
The constant database normally is created from an instructions directory by
running
.BR ipsvd-cdb (8).
.TP
.B \-n
Deny a new connection instead of starting
.I prog
to handle it, if there are no special intructions for the client that
initiated the connection.
.TP
.B \-E
no ucspi environment.
Do not set up TCP-related environment variables.
.TP
.B \-b \fIn
backlog.
Allow a backlog of approximately
.I n
TCP SYNs.
On some systems
.I n
is silently limited.
Default is 20.
.TP
.B \-H
Do not look up client's hostname in DNS.
.TP
.B \-v
verbose.
Print verbose messsages to standard output.
.SH SEE ALSO
ipsvd(7),
udpsvd(8),
ipsvd-instruct(5),
ipsvd-cdb(8)
.P
http://smarden.org/ipsvd/
.SH AUTHOR
Gerrit Pape <pape@smarden.org>
