.TH udpsvd 8
.SH NAME
udpsvd \- UDP/IP service daemon
.SH SYNOPSIS
.B udpsvd
[\-vh] [\-u
.I user\fR]
.I host
.I port
.I prog
.SH DESCRIPTION
.SH OPTIONS
.TP
.I host
.I host
either is a hostname, or a dotted-decimal IP address, or 0.
If
.I host
is 0,
.B udpsvd
accepts connections to any local IP address.
.TP
.I port
.B udpsvd
accepts connections to
.IR host :\fIport\fR.
.TP
.I prog
.I prog
consists of one or more arguments.
.TP
.B \-u \fIuser
drop permissions.
Switch user ID to
.IR user 's
UID, and group ID to
.IR user 's
primary GID after creating and binding to the socket.
.TP
.B -v
verbose.
Print verbose messaged to standard out.
.TP
.B \-h
lookup hostname.
.SH SEE ALSO
tcpsvd(8),
ipsvd-cdb(8)
.P
http://smarden.org/ipsvd/
.SH AUTHOR
Gerrit Pape <pape@smarden.org>
