#!/bin/sh -e

umask 022
test -d package || sh -cx '! : Wrong working directory.'
test -d src || sh -cx '! : Wrong working directory.'

here=`env - PATH=$PATH pwd`
parent=`dirname $here`

echo 'Creating symlink ipsvd -> ipsvd-1.1.1...'
rm -f ipsvd
ln -s ipsvd-1.1.1 ipsvd
mv -f ipsvd ..

echo 'Making command links in /command...'
mkdir -p /command/.
for i in `cat package/commands`; do
  rm -f /command/$i'{new}'
  ln -s $parent/ipsvd/command/$i /command/$i'{new}'
  mv -f /command/$i'{new}' /command/$i
done
if test -e /command/sslio; then
  echo 'Removing sslio, sslsvd from /command...'
  rm -f /command/sslio /command/sslsvd
fi
echo 'Making compatibility links in /usr/local/bin...'
mkdir -p /usr/local/bin/.
for i in `cat package/commands`; do
  rm -f /usr/local/bin/$i'{new}'
  ln -s /command/$i /usr/local/bin/$i'{new}'
  mv -f /usr/local/bin/$i'{new}' /usr/local/bin/$i
done
if test -e /usr/local/bin/sslio; then
  echo 'Removing sslio, sslsvd from /usr/local/bin...'
  rm -f /usr/local/bin/sslio /usr/local/bin/sslsvd
fi
